def _get_exception_message(exception):
